version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '3333:3333'
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3333

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - '80:80'
    depends_on:
      - backend